My GitHub login
HirokiMiyakura/fjord-books_app pull request #6
Opened 2021-05-17 17:08 UTC by HirokiMiyakura

2021-05-20 06:29 UTC, komagata requested changes

2021-05-20 06:29 UTC, komagata commented on .gitignore
> +/config/credentials.yml.enc
これは暗号化されているのでignoreしなくて良いと思います〜

2021-05-20 12:36 UTC, HirokiMiyakura commented on .gitignore
> +/config/credentials.yml.enc
こちら削除しました！

2021-05-21 04:51 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-05-23 23:52 UTC, merged